// Productos de Look-in Store. Para agotar uno: agotado: true. Tallas en stock: tallas: ['CH', 'M'].
// Nunca poner precios (se dan por DM en Instagram).
window.PRODUCTS = [
  { n: 1, name: 'Hellstar · Modelo 01', cat: 'hellstar', agotado: false, img: 'img/p01.jpg',
    desc: 'Playera negra con el logo Hellstar vertical y estrella en estampado blanco desgastado.',
    feats: ['Color negro', 'Estampado blanco efecto desgastado', 'Corte oversize', 'Talla: pregúntanos por DM'] },
  { n: 2, name: 'Hellstar · Modelo 02', cat: 'hellstar', agotado: false, img: 'img/p02.jpg',
    desc: 'Playera negra con logo Hellstar al frente, insignia ovalada y detalles de puntos tipo cielo estrellado.',
    feats: ['Color negro', 'Logo Hellstar e insignia ovalada', 'Detalles tipo cielo estrellado', 'Talla: pregúntanos por DM'] },
  { n: 3, name: 'Hellstar · Modelo 03', cat: 'hellstar', agotado: false, img: 'img/p03.jpg',
    desc: 'Playera negra con figura central rodeada de rayos y el logo Hellstar con estrella.',
    feats: ['Color negro', 'Gráfico grande al frente', 'Estampado gris claro', 'Talla: pregúntanos por DM'] },
  { n: 4, name: 'Hellstar · Modelo 04', cat: 'hellstar', agotado: false, img: 'img/p04.jpg',
    desc: 'Playera negra «Studios» con el emblema de perfil con flamas en estampado grande.',
    feats: ['Color negro', 'Texto «Studios» al frente', 'Emblema de perfil con flamas', 'Talla: pregúntanos por DM'] },
  { n: 5, name: 'Hellstar · Modelo 05', cat: 'hellstar', agotado: false, img: 'img/p05.jpg',
    desc: 'Playera negra con perfil de flamas y estrella en estilo telaraña, con lavado sutil.',
    feats: ['Color negro', 'Gráfico estilo telaraña', 'Lavado sutil', 'Talla: pregúntanos por DM'] },
  { n: 6, name: 'Hellstar · Modelo 06', cat: 'hellstar', agotado: false, img: 'img/p06.jpg',
    desc: 'Playera negra con la «H» de líneas en movimiento y la palabra «star».',
    feats: ['Color negro', 'Estampado beige claro', 'Diseño gráfico minimalista', 'Talla: pregúntanos por DM'] },
  { n: 7, name: 'Hellstar · Modelo 07', cat: 'hellstar', agotado: false, img: 'img/p07.jpg',
    desc: 'Playera negra con estrella y flamas al frente y detalles en las mangas.',
    feats: ['Color negro', 'Estrella y flamas al frente', 'Detalles en las mangas', 'Talla: pregúntanos por DM'] },
  { n: 8, name: 'Hellstar · Modelo 08', cat: 'hellstar', agotado: false, img: 'img/p08.jpg',
    desc: 'Playera negra con logo Hellstar, insignia «Godsfeed» y gráficos en ambas mangas.',
    feats: ['Color negro', 'Logo e insignias al frente', 'Gráficos en las mangas', 'Talla: pregúntanos por DM'] },
  { n: 9, name: 'Hellstar · Modelo 09', cat: 'hellstar', agotado: false, img: 'img/p09.jpg',
    desc: 'Playera blanca con letras estilo grafiti y un ángel a todo color.',
    feats: ['Color blanco', 'Gráfico a todo color', 'Letras estilo grafiti', 'Talla: pregúntanos por DM'] },
  { n: 10, name: 'Hellstar · Modelo 10', cat: 'hellstar', agotado: false, img: 'img/p10.jpg',
    desc: 'Playera blanca «Emotion» con figura alada a todo color y lavado vintage.',
    feats: ['Color blanco', 'Texto «Emotion»', 'Gráfico a todo color con lavado vintage', 'Talla: pregúntanos por DM'] },
  { n: 11, name: 'Essentials · Negra', cat: 'essentials', agotado: false, img: 'img/p11.jpg', tallas: ['CH', 'M'],
    desc: 'La básica que combina con todo: playera Essentials negra con «ESSENTIALS / FEAR OF GOD» tono sobre tono al frente.',
    feats: ['Color negro', 'Logo al frente tono sobre tono', 'Corte relajado', 'Tallas: CH y M'] },
  { n: 12, name: 'Essentials · Blanca', cat: 'essentials', agotado: false, img: 'img/p12.jpg', tallas: ['CH', 'M'],
    desc: 'Playera Essentials blanca hueso con «ESSENTIALS / FEAR OF GOD» en negro al frente. Limpia y fácil de combinar.',
    feats: ['Color blanco hueso', 'Logo al frente en negro', 'Corte relajado', 'Tallas: CH y M'] },
  { n: 13, name: 'Essentials · Gris', cat: 'essentials', agotado: false, img: 'img/p13.jpg', tallas: ['CH', 'M'],
    desc: 'Playera Essentials gris jaspeado con «ESSENTIALS / FEAR OF GOD» en negro al frente.',
    feats: ['Color gris jaspeado', 'Logo al frente en negro', 'Corte relajado', 'Tallas: CH y M'] },
];
